import { notFound } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { ClaimablePassportPreview } from "@/components/passports/claimable-passport-preview";
import { Card } from "@/components/ui/card";
import PublicProfilePage from "@/app/c/[userId]/page";
import { fetchClaimablePassportBySlug } from "@/lib/db/claimable-passports";
import { fetchPublicCandidateDataByPassportSlug } from "@/lib/db/projects";
import { createServerSupabaseClient } from "@/lib/supabase/server";

type PublicPassportSlugPageProps = {
  params: Promise<{
    slug: string;
  }>;
};

const PASSPORT_SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

export default async function PublicPassportSlugPage({ params }: PublicPassportSlugPageProps) {
  const { slug } = await params;
  if (!PASSPORT_SLUG_PATTERN.test(slug)) {
    notFound();
  }

  const supabase = await createServerSupabaseClient();
  const candidate = await fetchPublicCandidateDataByPassportSlug(supabase, slug);
  if (candidate) {
    return PublicProfilePage({
      params: Promise.resolve({
        userId: candidate.userId
      })
    });
  }

  const passport = await fetchClaimablePassportBySlug(slug);
  if (!passport) {
    notFound();
  }

  if (passport.status === "claimed" && passport.ownerUserId) {
    return PublicProfilePage({
      params: Promise.resolve({
        userId: passport.ownerUserId
      })
    });
  }

  const {
    data: { user }
  } = await supabase.auth.getUser();

  return (
    <AppShell userEmail={user?.email}>
      <ClaimablePassportPreview passport={{ ...passport, claimToken: null }} />
      <section className="editorial-container pt-8">
        <Card className="space-y-3">
          <p className="label-caps">Pre-claim Passport</p>
          {passport.status === "expired" ? (
            <>
              <h2 className="font-serif text-2xl text-[#16130f]">This Passport preview has expired</h2>
              <p className="text-sm leading-6 text-[#7b705f]">
                The public preview remains visible for review, but the private claim link must be regenerated by an admin.
              </p>
            </>
          ) : (
            <>
              <h2 className="font-serif text-2xl text-[#16130f]">This Passport is waiting to be claimed</h2>
              <p className="text-sm leading-6 text-[#7b705f]">
                The public path is separate from the secure claim link. Claiming still requires the private token sent by Merit.
              </p>
            </>
          )}
        </Card>
      </section>
    </AppShell>
  );
}
